samplesite/bboard/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from .views import (# index,
                    BbIndexView, BbByRubricView, BbCreateView,
                    BbDetailView, BbAddView, BbEditView, BbDeleteView, BbMonthView,
                    RedirectView, edit, rubrics, bbs
                    )

# Скобки потому что много строк, если 1 СТРОКА, тогда БЕЗ СКОБОК

app_name = 'bboard'

urlpatterns = [
    # path('add/', BbCreateView.as_view(), name='add'),

    # path('add/save/', add_save, name='add_save'),

    path('detail/<int:pk>/', BbDetailView.as_view(), name='detail'),
    path('add/', BbAddView.as_view(), name='add'),

    path('<int:rubric_id>/', BbByRubricView.as_view(), name='by_rubric'),
    # path('', index, name='index'),
    path('', BbIndexView.as_view(), name='index'),
    path('year/<int:year>/', RedirectView.as_view(), name='redirect'),
    path('<int:year>/<int:month>/', BbMonthView.as_view(), name='month'),
    path('update/<int:pk>/', edit, name='update'),
    path('delete/<int:pk>/', BbDeleteView.as_view(), name='delete'),

    path('rubrics/', rubrics, name='rubrics'),
    path('bbs/<int:rubric_id>/', bbs, name='bbs'),

    path('accounts/login/', LoginView.as_view(), name='login'),
    path('accounts/logout/', LogoutView.as_view(), name='logout'),
]

samplesite/samplesite/urls.py
from django.contrib import  admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('test/', include('testapp.urls', namespace='test')),
    path('', include('bboard.urls', namespace='bboard')),
]

samplesite/templates/_index.html
{% extends "layout/basic.html" %}


{% block content %}

    <p>
    {% for d in date_list %}
        {{ d.year }} /
        <a href="{% url 'bboard:month' year=d.year month=d.month %}">
            {{d.year}} - {{ d.month }}</a>
    {% endfor %}
    </p>


{% for bb in bbs %}
<div>
    <h2>
        <a href="{% url 'bboard:detail' pk=bb.pk %}">
            {{ bb.title }}</a>
    </h2>
        {#{bb.title}#}{{bb.title_and_price}}</h2>
    <p>{{bb.content}}</p>

    <p>
        <a href="{ % url 'by_rubric' rubric.pk %}">{{ bb.rubric.name }}</a>
    </p>

    <p>{{bb.pusblished|date:"d.m.Y H:i:s"}}</p>
</div>
{% endfor %}
{% endblock %}

samplesite/templates/add.html
{% extends "layout/basic.html" %}

{% block title %}Добавление изображения{% endblock %}

{% block content %}
<h2> Добавление изображения</h2>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}

    <p><button type="submit" class="btn btn-primary">Добавить</button></p>
</form>
{% endblock %}

samplesite/templates/by_rubric.html
{% extends "layout/basic.html" %}

{% block title %}{{ current_rubric.name }}{% endblock %}

{% block content %}

<h2>Рубрика: {{ current_rubric.name }}</h2>

<div>
    <a href="{% url 'bboard:index' %}">Главная</a>
    {% for rubric in rubrics %}
        <a href="{% url 'bboard:by_rubric' rubric.pk %}">{{ rubric.name }}</a>
    {% endfor %}

</div>

{% for bb in bbs %}

<div>
    <h2>{{bb.title}}</h2>
    <p>{{bb.content}}</p>
    <p>{{bb.pusblished|date:"d.m.Y H:i:s"}}</p>
</div>
{% endfor %}
{% endblock %}

</body>
</html>

samplesite/templates/create.html
{% extends "layout/basic.html" %}

{% block title %} Добавление объявления{% endblock %}

{% block content %}

<h2>Добавление объявления</h2>

{% if form.is_multipart %}

    <form method="post" enctype="multipart/form-data">
{% else %}
    <form method="post">
{% endif %}
    </form>
    {% csrf_token %}


{#    {{ form.as_p }} #}

<table>
    {{ form }}
</table>


{#    <input type="submit" value="Добавить"> #}


<button type="submit" class="btn btn-primary">Добавить</button>
</form>
{% endblock %}


<!--<div>-->
<!--    <a href="{% url 'index' %}">Главная</a>-->
<!--    {% for rubric in rubrics %}-->
<!--        <a href="{% url 'by_rubric' rubric.pk %}">{{ rubric.name }}</a>-->
<!--    {% endfor %}-->
<!--</div>-->

<!--<form method="post">-->
<!--    {% csrf_token %}-->
<!--    {{ form.as_p }}-->
<!--    <input type="submit" value="Добавить">-->
<!--</form>-->

<!--</body>-->
<!--</html>-->

samplesite/templates/index.html
{% extends "layout/basic.html" %}

{% block content %}

    {{ block.super }}

    <p>
    {% for d in date_list %}
        {{ d.year }} /
        <a href="{% url 'bboard:month' year=d.year month=d.month %}">
            {{d.year}} - {{ d.month }}</a>
    {% endfor %}
    </p>


{% for bb in bbs %}
{#% cycle 'b1' 'b2' 'b3' as currentclass %#}

<div class="{% cycle 'b1' 'b2' 'b3' %}">

    <h2>
        {% url 'bboard:detail' bb.pk as detail_url %}
        <a href="{% url 'bboard:detail' pk=bb.pk %}">
            {{ forloop.counter }} - {{ bb.title_and_price }}
            {% if forloop.first == True %}
                (Первое Объявление)
            {% elif forloop.last == True %}
                (Последнее Объявление)
            {% endif %}</a>
    </h2>

    <p>{{  bb.content|cut:'Lorem'  }}</p>
<!--    cut - слово не будет показываться в тексте -->

    {% ifchanged bb.rubric.name %}

    <p>
        <a href="{ % url 'by_rubric' bb.rubric.pk %}">
            {{ bb.rubric.name }}</a>
    </p>
    {% endifchanged %}


    <p>{{bb.pusblished|date:"d.m.Y H:i:s"}}</p>

    {% firstof bb.phone bb.email 'На деревню дедушке' %}

</div>
{% empty %}

    <p>Объявлений нет!!!</p>

{% endfor %}

<div>
    {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number }}">&lt;</a>
        &nbsp; &nbsp; | &nbsp; &nbsp;
    {% endif %}

    Страница №{{ page.number }} из {{ page.paginator.num_pages }}

    {% if page.has_next %}
        &nbsp; &nbsp; | &nbsp; &nbsp;
        <a href="?page={{ page.next_page_number }}">&gt;</a>
    {% endif %}

</div>

{% include 'includes/inc_paginator.html' %}

{% endblock content %}

samplesite/templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
</head>
<body>
<h1>{{ title }}</h1>
{% for bb in bbs %}
    <p>{{ bb }}</p>
{% endfor %}

<h2>{{ res }}</h2>
<h3>{{ res.url_name }}</h3>
<h2>{{ res.view_name }}</h2>

</body>
</html>