samplesite/bboard/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from .views import (# index,
                    BbIndexView, BbByRubricView, BbCreateView,
                    BbDetailView, BbAddView, BbEditView, BbDeleteView, BbMonthView,
                    RedirectView, edit, rubrics, bbs
                    )

# Скобки потому что много строк, если 1 СТРОКА, тогда БЕЗ СКОБОК

app_name = 'bboard'

urlpatterns = [
    # path('add/', BbCreateView.as_view(), name='add'),

    # path('add/save/', add_save, name='add_save'),

    path('detail/<int:pk>/', BbDetailView.as_view(), name='detail'),
    path('add/', BbAddView.as_view(), name='add'),

    path('<int:rubric_id>/', BbByRubricView.as_view(), name='by_rubric'),
    # path('', index, name='index'),
    path('', BbIndexView.as_view(), name='index'),
    path('year/<int:year>/', RedirectView.as_view(), name='redirect'),
    path('<int:year>/<int:month>/', BbMonthView.as_view(), name='month'),
    path('update/<int:pk>/', edit, name='update'),
    path('delete/<int:pk>/', BbDeleteView.as_view(), name='delete'),

    path('rubrics/', rubrics, name='rubrics'),
    path('bbs/<int:rubric_id>/', bbs, name='bbs'),

    path('accounts/login/', LoginView.as_view(), name='login'),
    path('accounts/logout/', LogoutView.as_view(), name='logout'),
]

samplesite/samplesite/urls.py
from django.contrib import  admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('test/', include('testapp.urls', namespace='test')),
    path('', include('bboard.urls', namespace='bboard')),
]

samplesite/templates/includes/_inc_paginator.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

{% if page.has_other_pages %}

    <nav aria-label="pagination">
      <ul class="pagination">

        {% if page.has_previous %}
        <li class="page-item disabled">
          <a class="page-link"
             href="?page={{ page.previous_page_number }}">Previous</a>
        </li>
        {% endif %}



        <li class="page-item"><a class="page-link" href="#">1</a></li>
        <li class="page-item active" aria-current="page">
          <a class="page-link" href="#">2</a>
        </li>
        <li class="page-item"><a class="page-link" href="#">3</a></li>



        {% for p in page.paginator.page_range %}
          {% if not p == page.number %}
          <li class="page-item">
            <a class="page-link" href="?page={{ p }}">{{ p }}</a>
          </li>
        {% else %}
        <li class="page-item active" aria-current="page">
          <a class="page-link" href="#">2</a>
        </li>
          {% endif %}
        {% endfor %}


        {% if page.has_next %}
        <li class="page-item">
          <a class="page-link"
             href="?page={{ page.next_page_number">Next</a>
        </li>
        {% endif %}

      </ul>
</nav>

{% endif %}

</body>
</html>

samplesite/templates/includes/inc_main_menu.html
{% load static %}

<!doctype html>
<html lang="\">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}Главная{% endblock %} :: Доска объявлений</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>

<header>
    <h1>Объявления</h1>
</header>

<nav>
    <a href="{% url 'bboard:index' %}">Главная</a>
    <a href="{% url 'bboard:add' %}">Добавить</a>
    <a href="{% url 'bboard:login' %}" class="text-danger">Войти</a>

    {#{{ rubrics.0 }}#}

    {% for rubric in rubrics %}
        {% with bb_count=rubric.cnt %}
        <a href="{{ rubric.get_absolute_url }}">
{#            {{ rubric }} ({{ rubric.cnt }})</a> #}
            {% filter upper %}
                {{ rubric.name }}
            {% endfilter %}
            ({{ bb_count }})</a>
        {% endwith %}
    {% endfor %}
</nav>

samplesite/templates/includes/inc_paginator.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

{% if page.has_other_pages %}

    <nav aria-label="pagination">
      <ul class="pagination">

        {% if page.has_previous %}
        <li class="page-item disabled">
          <a class="page-link"
             href="?page={{ page.previous_page_number }}">Previous</a>
        </li>
        {% endif %}



        <li class="page-item"><a class="page-link" href="#">1</a></li>
        <li class="page-item active" aria-current="page">
          <a class="page-link" href="#">2</a>
        </li>
        <li class="page-item"><a class="page-link" href="#">3</a></li>



        {% for p in page.paginator.page_range %}
          {% if not p == page.number %}
          <li class="page-item">
            <a class="page-link" href="?page={{ p }}">{{ p }}</a>
          </li>
        {% else %}
        <li class="page-item active" aria-current="page">
          <a class="page-link" href="#">2</a>
        </li>
          {% endif %}
        {% endfor %}


        {% if page.has_next %}
        <li class="page-item">
          <a class="page-link"
             href="?page={{ page.next_page_number">Next</a>
        </li>
        {% endif %}

      </ul>
</nav>

{% endif %}

</body>
</html>